#!/usr/bin/env bash
# Creates a Debug controller, updates admin docs and registers route in routes/api.php
set -euo pipefail

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 ControllerName" >&2
  exit 2
fi

CONTROLLER_NAME="$1"
SNAKE_NAME="$(echo "$CONTROLLER_NAME" | sed -r 's/([A-Z])/_\L\1/g' | sed -r 's/^_//; s/_controller$//')"
KEBAB="$(echo "$SNAKE_NAME" | tr '_' '-')"
CONTROLLER_DIR="app/Http/Controllers/Debug"
CONTROLLER_FILE="$CONTROLLER_DIR/$CONTROLLER_NAME.php"
TEMPLATE="$(dirname "$0")/controller_template.php"

if [ -f "$CONTROLLER_FILE" ]; then
  echo "Controller already exists: $CONTROLLER_FILE" >&2
  exit 3
fi

mkdir -p "$CONTROLLER_DIR"
sed "s/__CONTROLLER_NAME__/$CONTROLLER_NAME/g" "$TEMPLATE" > "$CONTROLLER_FILE"
echo "Created $CONTROLLER_FILE"

# Append documentation to dev-docs/admin-endpoints.md
DOC_FILE="dev-docs/admin-endpoints.md"
DOC_ENTRY="\n### Debug — $CONTROLLER_NAME\n\nEndpoint de diagnóstico implementado pelo controller `app/Http/Controllers/Debug/$CONTROLLER_NAME.php`.\n\n```\nGET /api/admin/debug/$KEBAB\n```\n\n**Autenticação:** `auth:sanctum` (Bearer token).\n\n**Implementação:** `app/Http/Controllers/Debug/$CONTROLLER_NAME.php`\n\n"

grep -q "Debug — $CONTROLLER_NAME" "$DOC_FILE" || printf "%s" "$DOC_ENTRY" >> "$DOC_FILE" && echo "Appended docs to $DOC_FILE"

# Register route at end of routes/api.php near debug routes — append import and route
ROUTES_FILE="routes/api.php"

# Add use import if not present
IMPORT_LINE="use App\\Http\\Controllers\\Debug\\$CONTROLLER_NAME;"
if ! grep -Fq "$IMPORT_LINE" "$ROUTES_FILE"; then
  # Insert after other App\Http\Controllers\Debug\ imports if any, otherwise after first use block
  awk -v imp="$IMPORT_LINE" '
  BEGIN{printed=0}
  {print $0}
  /use App::/ { }
  END{}
' "$ROUTES_FILE" > "$ROUTES_FILE.tmp" && mv "$ROUTES_FILE.tmp" "$ROUTES_FILE"
  # simple append at top imports block: find first "use App\\Http\\Controllers" and insert after
  awk -v imp="$IMPORT_LINE" 'NR==1{printed=0} {print} /use App\\Http\\Controllers\\Debug/ && printed==0 {print imp; printed=1}' "$ROUTES_FILE" > "$ROUTES_FILE.tmp" || true
  if [ -s "$ROUTES_FILE.tmp" ]; then mv "$ROUTES_FILE.tmp" "$ROUTES_FILE"; else rm -f "$ROUTES_FILE.tmp"; fi
  # fallback: if not inserted, try to insert after first large use block
  if ! grep -Fq "$IMPORT_LINE" "$ROUTES_FILE"; then
    sed -i "1i$IMPORT_LINE" "$ROUTES_FILE"
  fi
  echo "Added import to $ROUTES_FILE"
fi

# Append route
ROUTE_LINE="Route::get('admin/debug/$KEBAB', [$CONTROLLER_NAME::class, '__invoke']);"
if ! grep -Fq "$ROUTE_LINE" "$ROUTES_FILE"; then
  printf "\n// Debug route generated by skills: %s\n%s\n" "$(date --iso-8601=seconds)" "$ROUTE_LINE" >> "$ROUTES_FILE"
  echo "Appended route to $ROUTES_FILE"
fi

echo "Done: $CONTROLLER_FILE, $DOC_FILE, $ROUTES_FILE"

# Suggest a semantic commit message in Portuguese (do not commit automatically)
COMMIT_MSG="chore(debug): adicionar controller $CONTROLLER_NAME, rota /admin/debug/$KEBAB e documentação"
echo "\nSugestão de commit (semântico, em português):"
echo "$COMMIT_MSG"
echo "Execute os comandos a seguir para revisar e commitar as mudanças:"
echo "  git add $CONTROLLER_FILE $DOC_FILE $ROUTES_FILE"
echo "  git commit -m \"$COMMIT_MSG\""
